### ISSUE TITLE
pretrained checkpoint link is dead

### ISSUE THREAD

**Issue by TikaToka** [anonrabit/DialFRED#13]
Hello @xfgao, @cpbara , and @anonrabit .
First of all, thank you for sharing amazing work!

By the way, can you give a new link to download pretrained checkpoint?

Thank you in advance.

**Comment by xfgao** [comment]
Which link are you talking about? 

For the ET checkpoint please check this thread since we don't own it: https://github.com/alexpashevich/E.T./issues/13

For DialFRED checkpoints in [`scripts/fetch_model_checkpt.sh`](https://github.com/xfgao/DialFRED/blob/main/scripts/fetch_model_checkpt.sh), I think the links are still working.

**Comment by TikaToka** [comment]
I was talking about the former one. Thank you for your quick response!
